#!/bin/bash

# Amy App Stack
# (c)2015 C. Byerley

BASE=$(pwd)

clear

echo ' '
echo 'Got Awesome? Here we go!'
echo ' '

sleep 1

cd $BASE
npm install &

cd $BASE/client
bower install &

clear

echo ' '
echo 'Now adding awesomeness, please wait...'
echo ' '

wait %1 %2

cd $BASE

echo ' '
echo 'You got Awesome! Bye!'
echo ' '
